### ISSUE TITLE
could it support a nested structure?

### ISSUE THREAD

**Issue by Morriz** [Bhoos/react-native-theming#12] opened 2018-12-31 00:42 UTC
Hi, I would love it if I can do this:
```
createStyle({
  someModule: {
    someStyle: 'red'
  },
  anotherModule: ...
}
```
and then refer to it like '@someModule.someStyle'. As I have quite some styles grouped like that it would be hard to flatten into a list.

**Comment by jonathanroze** [comment] 2020-07-03 10:28
Pretty good question, any news about that ?

**Comment by dapicester** [comment] 2021-07-05 08:37
This seems a duplicate of #14, actually solved in #31.

**Closed as completed** 2021-07-20 04:11 UTC
